import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';
const SECRET_KEY = process.env.APP_SECRET; // Must be exactly 32 bytes (64 hex characters)
const IV_LENGTH = 16;
const SALT_LENGTH = 64;
const TAG_LENGTH = 16;

/**
 * Encrypts a string into a URL-safe base64 structure containing [iv]:[salt]:[auth_tag]:[encrypted_content]
 */
export function encryptData(text: string | null | undefined): string | null {
  if (!text) return null;
  
  if (!SECRET_KEY || SECRET_KEY.length < 64) {
    console.warn("WARNING: APP_SECRET is missing or invalid. Returning plain text to avoid system crash. Set APP_SECRET to a 32-byte hex string in your environment.");
    return text;
  }

  try {
    const iv = crypto.randomBytes(IV_LENGTH);
    const salt = crypto.randomBytes(SALT_LENGTH);
    
    // In AES-GCM we can derive a key from user secret + salt to strengthen against rainbow tables
    const key = crypto.pbkdf2Sync(Buffer.from(SECRET_KEY, 'hex'), salt, 100000, 32, 'sha512');

    const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
    
    let encrypted = cipher.update(text, 'utf8', 'hex');
    encrypted += cipher.final('hex');

    const authTag = cipher.getAuthTag();

    // Payload: IV : SALT : AUTHTAG : ENCRYPTED_CONTENT
    return `${iv.toString('hex')}:${salt.toString('hex')}:${authTag.toString('hex')}:${encrypted}`;
  } catch (err) {
    console.error("Encryption failed:", err);
    return text; // Fallback to avoid catastrophic dataloss in case of bad buffer sizes
  }
}

/**
 * Decrypts a payload generated by encryptData(). Returns raw string.
 */
export function decryptData(payload: string | null | undefined): string | null {
  if (!payload) return null;
  if (!payload.includes(':')) {
    // If it's not our encrypted payload format (e.g. legacy plain text keys), just return them raw to prevent breaking old users
    return payload;
  }

  if (!SECRET_KEY || SECRET_KEY.length < 64) {
    return payload; // Fallback to raw if secret misconfigured
  }

  try {
    const textParts = payload.split(':');
    const iv = Buffer.from(textParts[0], 'hex');
    const salt = Buffer.from(textParts[1], 'hex');
    const authTag = Buffer.from(textParts[2], 'hex');
    const encryptedText = textParts[3];

    // Re-derive key
    const key = crypto.pbkdf2Sync(Buffer.from(SECRET_KEY, 'hex'), salt, 100000, 32, 'sha512');

    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);
    
    let decrypted = decipher.update(encryptedText, 'hex', 'utf8');
    decrypted += decipher.final('utf8');
    
    return decrypted;
  } catch (err) {
    console.error("Decryption failed:", err);
    return payload; // Returns the raw scrambled payload safely on failure to avoid throwing 500s directly
  }
}
